# Generated by Django 5.1.4 on 2024-12-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
