# Generated by Django 5.1.4 on 2024-12-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
